// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/rider_location.proto

// Protobuf Java Version: 3.25.2
package com.nordstrom.kafka.connect.eventbus;

public final class RiderLocationOuterClass {
  private RiderLocationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_deliveryhero_eventbus_RiderLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_deliveryhero_eventbus_RiderLocation_Courier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_deliveryhero_eventbus_RiderLocation_Courier_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_deliveryhero_eventbus_RiderLocation_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_deliveryhero_eventbus_RiderLocation_Location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_deliveryhero_eventbus_RiderLocation_Battery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_deliveryhero_eventbus_RiderLocation_Battery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_deliveryhero_eventbus_RiderLocation_Network_info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_deliveryhero_eventbus_RiderLocation_Network_info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_deliveryhero_eventbus_RiderLocation_Connection_info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_deliveryhero_eventbus_RiderLocation_Connection_info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_deliveryhero_eventbus_RiderLocation_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_deliveryhero_eventbus_RiderLocation_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_deliveryhero_eventbus_RiderLocation_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_deliveryhero_eventbus_RiderLocation_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_deliveryhero_eventbus_RiderLocation_MessageWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_deliveryhero_eventbus_RiderLocation_MessageWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'src/main/resources/rider_location.prot" +
      "o\022\031com.deliveryhero.eventbus\032\037google/pro" +
      "tobuf/timestamp.proto\"\246\t\n\rRiderLocation\022" +
      "\014\n\004Type\030\001 \001(\t\022\021\n\tMessageId\030\002 \001(\t\022\020\n\010Topi" +
      "cArn\030\003 \001(\t\022H\n\007Message\030\004 \001(\01327.com.delive" +
      "ryhero.eventbus.RiderLocation.MessageWra" +
      "pper\022-\n\tTimestamp\030\005 \001(\0132\032.google.protobu" +
      "f.Timestamp\022\030\n\020SignatureVersion\030\006 \001(\t\022\021\n" +
      "\tSignature\030\007 \001(\t\022\026\n\016SigningCertURL\030\010 \001(\t" +
      "\022\026\n\016UnsubscribeURL\030\t \001(\t\032&\n\007Courier\022\n\n\002i" +
      "d\030\001 \001(\r\022\017\n\007user_id\030\002 \001(\r\032/\n\010Location\022\020\n\010" +
      "latitude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\032(\n\007Bat" +
      "tery\022\016\n\006status\030\001 \001(\t\022\r\n\005level\030\002 \001(\005\032\016\n\014N" +
      "etwork_info\032^\n\017Connection_info\022K\n\014networ" +
      "k_info\030\001 \001(\01325.com.deliveryhero.eventbus" +
      ".RiderLocation.Network_info\032\252\002\n\010Metadata" +
      "\022\r\n\005speed\030\001 \001(\r\022\017\n\007heading\030\002 \001(\r\022\020\n\010accu" +
      "racy\030\003 \001(\r\022\025\n\rmock_location\030\004 \001(\010\022A\n\007bat" +
      "tery\030\005 \001(\01320.com.deliveryhero.eventbus.R" +
      "iderLocation.Battery\022Q\n\017connection_info\030" +
      "\006 \001(\01328.com.deliveryhero.eventbus.RiderL" +
      "ocation.Connection_info\022\021\n\tdevice_id\030\007 \001" +
      "(\t\022\020\n\010platform\030\010 \001(\t\022\032\n\022roadrunner_versi" +
      "on\030\t \001(\t\032\323\001\n\004Data\022A\n\007courier\030\001 \001(\01320.com" +
      ".deliveryhero.eventbus.RiderLocation.Cou" +
      "rier\022C\n\010location\030\002 \001(\01321.com.deliveryher" +
      "o.eventbus.RiderLocation.Location\022C\n\010met" +
      "adata\030\003 \001(\01321.com.deliveryhero.eventbus." +
      "RiderLocation.Metadata\032\225\001\n\016MessageWrappe" +
      "r\022\014\n\004type\030\001 \001(\t\022;\n\004data\030\002 \001(\0132-.com.deli" +
      "veryhero.eventbus.RiderLocation.Data\022\024\n\014" +
      "country_code\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\t\022\017\n" +
      "\007version\030\005 \001(\rB(\n$com.nordstrom.kafka.co" +
      "nnect.eventbusP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_deliveryhero_eventbus_RiderLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor,
        new java.lang.String[] { "Type", "MessageId", "TopicArn", "Message", "Timestamp", "SignatureVersion", "Signature", "SigningCertURL", "UnsubscribeURL", });
    internal_static_com_deliveryhero_eventbus_RiderLocation_Courier_descriptor =
      internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor.getNestedTypes().get(0);
    internal_static_com_deliveryhero_eventbus_RiderLocation_Courier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_deliveryhero_eventbus_RiderLocation_Courier_descriptor,
        new java.lang.String[] { "Id", "UserId", });
    internal_static_com_deliveryhero_eventbus_RiderLocation_Location_descriptor =
      internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor.getNestedTypes().get(1);
    internal_static_com_deliveryhero_eventbus_RiderLocation_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_deliveryhero_eventbus_RiderLocation_Location_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_com_deliveryhero_eventbus_RiderLocation_Battery_descriptor =
      internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor.getNestedTypes().get(2);
    internal_static_com_deliveryhero_eventbus_RiderLocation_Battery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_deliveryhero_eventbus_RiderLocation_Battery_descriptor,
        new java.lang.String[] { "Status", "Level", });
    internal_static_com_deliveryhero_eventbus_RiderLocation_Network_info_descriptor =
      internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor.getNestedTypes().get(3);
    internal_static_com_deliveryhero_eventbus_RiderLocation_Network_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_deliveryhero_eventbus_RiderLocation_Network_info_descriptor,
        new java.lang.String[] { });
    internal_static_com_deliveryhero_eventbus_RiderLocation_Connection_info_descriptor =
      internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor.getNestedTypes().get(4);
    internal_static_com_deliveryhero_eventbus_RiderLocation_Connection_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_deliveryhero_eventbus_RiderLocation_Connection_info_descriptor,
        new java.lang.String[] { "NetworkInfo", });
    internal_static_com_deliveryhero_eventbus_RiderLocation_Metadata_descriptor =
      internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor.getNestedTypes().get(5);
    internal_static_com_deliveryhero_eventbus_RiderLocation_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_deliveryhero_eventbus_RiderLocation_Metadata_descriptor,
        new java.lang.String[] { "Speed", "Heading", "Accuracy", "MockLocation", "Battery", "ConnectionInfo", "DeviceId", "Platform", "RoadrunnerVersion", });
    internal_static_com_deliveryhero_eventbus_RiderLocation_Data_descriptor =
      internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor.getNestedTypes().get(6);
    internal_static_com_deliveryhero_eventbus_RiderLocation_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_deliveryhero_eventbus_RiderLocation_Data_descriptor,
        new java.lang.String[] { "Courier", "Location", "Metadata", });
    internal_static_com_deliveryhero_eventbus_RiderLocation_MessageWrapper_descriptor =
      internal_static_com_deliveryhero_eventbus_RiderLocation_descriptor.getNestedTypes().get(7);
    internal_static_com_deliveryhero_eventbus_RiderLocation_MessageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_deliveryhero_eventbus_RiderLocation_MessageWrapper_descriptor,
        new java.lang.String[] { "Type", "Data", "CountryCode", "Timestamp", "Version", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
