// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/rider_location.proto

// Protobuf Java Version: 3.25.2
package com.nordstrom.kafka.connect.eventbus;

public interface RiderLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.deliveryhero.eventbus.RiderLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>.com.deliveryhero.eventbus.RiderLocation.Data data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.com.deliveryhero.eventbus.RiderLocation.Data data = 2;</code>
   * @return The data.
   */
  com.nordstrom.kafka.connect.eventbus.RiderLocation.Data getData();
  /**
   * <code>.com.deliveryhero.eventbus.RiderLocation.Data data = 2;</code>
   */
  com.nordstrom.kafka.connect.eventbus.RiderLocation.DataOrBuilder getDataOrBuilder();

  /**
   * <code>string country_code = 3;</code>
   * @return The countryCode.
   */
  java.lang.String getCountryCode();
  /**
   * <code>string country_code = 3;</code>
   * @return The bytes for countryCode.
   */
  com.google.protobuf.ByteString
      getCountryCodeBytes();

  /**
   * <code>string timestamp = 4;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 4;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>uint32 version = 5;</code>
   * @return The version.
   */
  int getVersion();
}
